export const SOLVER_BENCHMARK_SUITES = {
  "advanced-math": [
    {
      id: "linear-equation",
      category: "simple algebra",
      canonicalText: "Solve x + 35^2 = 0.",
      canonicalLatex: "x+35^2=0",
      expectedFinalLatex: "x=-1225",
      expectedNumeric: -1225,
      tolerance: 1e-9,
      requiredConcepts: ["evaluate power", "linear equation"],
      correctRejectionAcceptable: false,
    },
    {
      id: "quadratic-two-roots",
      category: "polynomial equations",
      canonicalText: "Solve 3x^2 + 5x - 22 = 0.",
      canonicalLatex: "3x^2+5x-22=0",
      expectedFinalLatex: "x=\\frac{-5\\pm\\sqrt{289}}{6}",
      requiredConcepts: ["factoring or quadratic formula"],
      symbolicOnlyAcceptable: true,
      correctRejectionAcceptable: false,
    },
    {
      id: "perfect-square-root",
      category: "polynomial equations",
      canonicalText: "Solve x^2 + 88x + 1936 = 0.",
      canonicalLatex: "x^2+88x+1936=0",
      expectedFinalLatex: "x=-44",
      expectedNumeric: -44,
      tolerance: 1e-9,
      requiredConcepts: ["perfect square"],
      correctRejectionAcceptable: false,
    },
    {
      id: "substitution-integral",
      category: "substitution integrals",
      canonicalText: "Evaluate the integral of 2x cos(x^2) from 0 to sqrt(pi).",
      canonicalLatex: "\\int_0^{\\sqrt{\\pi}}2x\\cos(x^2)\\,dx",
      expectedFinalLatex: "0",
      expectedNumeric: 0,
      tolerance: 1e-8,
      requiredConcepts: ["u-substitution"],
      correctRejectionAcceptable: false,
    },
    {
      id: "log-arctan-improper",
      category: "improper integrals",
      canonicalText: "Evaluate the integral from 0 to infinity of ln(1+x^2) arctan(x) divided by x(1+x^2).",
      canonicalLatex: "\\int_0^\\infty \\frac{\\ln(1+x^2)\\arctan x}{x(1+x^2)}\\,dx",
      expectedFinalLatex: "\\frac{\\pi}{2}\\ln^2 2",
      expectedNumeric: 0.7546938294602481,
      tolerance: 3.1e-4,
      requiredConcepts: ["improper integral", "numerical cross-check"],
      correctRejectionAcceptable: true,
    },
    {
      id: "gaussian-halfline",
      category: "improper integrals",
      canonicalText: "Evaluate the integral of exp(-x^2) from 0 to infinity.",
      canonicalLatex: "\\int_0^\\infty e^{-x^2}\\,dx",
      expectedFinalLatex: "\\frac{\\sqrt{\\pi}}{2}",
      expectedNumeric: 0.886226925452758,
      tolerance: 1e-6,
      requiredConcepts: ["Gaussian integral"],
      correctRejectionAcceptable: false,
    },
    {
      id: "sine-square",
      category: "trigonometric integrals",
      canonicalText: "Evaluate the integral of sin^2 x from 0 to pi.",
      canonicalLatex: "\\int_0^\\pi \\sin^2 x\\,dx",
      expectedFinalLatex: "\\frac{\\pi}{2}",
      expectedNumeric: 1.5707963267948966,
      tolerance: 1e-6,
      requiredConcepts: ["trig identity"],
      correctRejectionAcceptable: false,
    },
    {
      id: "tan-log-integral",
      category: "trigonometric integrals",
      canonicalText: "Evaluate the integral of ln(cos x) from 0 to pi/2.",
      canonicalLatex: "\\int_0^{\\pi/2}\\ln(\\cos x)\\,dx",
      expectedFinalLatex: "-\\frac{\\pi}{2}\\ln 2",
      expectedNumeric: -1.088793045151801,
      tolerance: 1e-6,
      requiredConcepts: ["classic logarithmic trig integral"],
      correctRejectionAcceptable: false,
    },
    {
      id: "basel-series",
      category: "infinite series",
      canonicalText: "Evaluate the infinite series sum from n=1 to infinity of 1/n^2.",
      canonicalLatex: "\\sum_{n=1}^\\infty\\frac{1}{n^2}",
      expectedFinalLatex: "\\frac{\\pi^2}{6}",
      expectedNumeric: 1.6449340668482264,
      tolerance: 1e-6,
      requiredConcepts: ["Basel problem"],
      correctRejectionAcceptable: false,
    },
    {
      id: "geometric-series",
      category: "infinite series",
      canonicalText: "Evaluate sum from n=0 to infinity of (1/3)^n.",
      canonicalLatex: "\\sum_{n=0}^\\infty\\left(\\frac{1}{3}\\right)^n",
      expectedFinalLatex: "\\frac{3}{2}",
      expectedNumeric: 1.5,
      tolerance: 1e-9,
      requiredConcepts: ["geometric series"],
      correctRejectionAcceptable: false,
    },
    {
      id: "double-integral-rectangle",
      category: "multivariable integrals",
      canonicalText: "Evaluate the double integral of x+y over 0<=x<=1, 0<=y<=2.",
      canonicalLatex: "\\int_0^1\\int_0^2 (x+y)\\,dy\\,dx",
      expectedFinalLatex: "3",
      expectedNumeric: 3,
      tolerance: 1e-9,
      requiredConcepts: ["iterated integral"],
      correctRejectionAcceptable: false,
    },
    {
      id: "polar-disk",
      category: "multivariable integrals",
      canonicalText: "Evaluate the integral of x^2+y^2 over the unit disk.",
      canonicalLatex: "\\iint_{x^2+y^2\\le 1}(x^2+y^2)\\,dA",
      expectedFinalLatex: "\\frac{\\pi}{2}",
      expectedNumeric: 1.5707963267948966,
      tolerance: 1e-6,
      requiredConcepts: ["polar coordinates", "Jacobian"],
      correctRejectionAcceptable: false,
    },
    {
      id: "stokes-paraboloid",
      category: "Stokes/Green problems",
      canonicalText: "Use Stokes theorem for the upward paraboloid z=9-x^2-y^2 above z=0.",
      canonicalLatex: "\\iint_S (\\nabla\\times\\mathbf F)\\cdot\\mathbf n\\,dS",
      expectedFinalLatex: "\\oint_C\\mathbf F\\cdot d\\mathbf r",
      requiredConcepts: ["Stokes theorem", "boundary orientation"],
      symbolicOnlyAcceptable: true,
      correctRejectionAcceptable: true,
    },
    {
      id: "green-ellipse",
      category: "Stokes/Green problems",
      canonicalText: "Use Green's theorem on the ellipse x^2/4+y^2/9=1.",
      canonicalLatex: "\\oint_C P\\,dx+Q\\,dy",
      requiredConcepts: ["Green theorem", "ellipse parameterization", "Jacobian"],
      symbolicOnlyAcceptable: true,
      correctRejectionAcceptable: true,
    },
    {
      id: "parameter-integral",
      category: "symbolic parameter problems",
      canonicalText: "Evaluate integral from 0 to 1 of a x dx for parameter a.",
      canonicalLatex: "\\int_0^1 ax\\,dx",
      expectedFinalLatex: "\\frac{a}{2}",
      requiredConcepts: ["parameter treated symbolically"],
      symbolicOnlyAcceptable: true,
      correctRejectionAcceptable: false,
    },
    {
      id: "differentiate-parameter",
      category: "symbolic parameter problems",
      canonicalText: "Differentiate a x^2 + b x with respect to x.",
      canonicalLatex: "\\frac{d}{dx}(ax^2+bx)",
      expectedFinalLatex: "2ax+b",
      requiredConcepts: ["parameter derivative"],
      symbolicOnlyAcceptable: true,
      correctRejectionAcceptable: false,
    },
    {
      id: "non-elementary-erf",
      category: "no elementary closed form",
      canonicalText: "Find an antiderivative of exp(-x^2).",
      canonicalLatex: "\\int e^{-x^2}\\,dx",
      expectedFinalLatex: "\\frac{\\sqrt{\\pi}}{2}\\operatorname{erf}(x)+C",
      requiredConcepts: ["non-elementary antiderivative", "erf"],
      symbolicOnlyAcceptable: true,
      correctRejectionAcceptable: true,
    },
    {
      id: "ocr-normalized-quadratic",
      category: "OCR-normalized canonical inputs",
      canonicalText: "Solve 3 x squared plus 5 x minus 22 equals 0.",
      canonicalLatex: "3x^2+5x-22=0",
      expectedFinalLatex: "x=2\\quad\\text{or}\\quad x=-\\frac{11}{3}",
      requiredConcepts: ["OCR canonical latex"],
      symbolicOnlyAcceptable: true,
      correctRejectionAcceptable: false,
    },
    {
      id: "undefined-symbol-regression",
      category: "known validator regression cases",
      canonicalText: "Evaluate a series without introducing Bernoulli coefficient placeholders.",
      canonicalLatex: "\\sum_{n=1}^\\infty\\frac{1}{n^2}",
      expectedFinalLatex: "\\frac{\\pi^2}{6}",
      expectedNumeric: 1.6449340668482264,
      tolerance: 1e-6,
      requiredConcepts: ["bound summation index", "no undefined symbols"],
      correctRejectionAcceptable: true,
    },
    {
      id: "wrong-answer-rejection-regression",
      category: "known validator regression cases",
      canonicalText: "Evaluate the improper logarithmic arctangent integral.",
      canonicalLatex: "\\int_0^\\infty \\frac{\\ln(1+x^2)\\arctan x}{x(1+x^2)}\\,dx",
      expectedFinalLatex: "\\frac{\\pi}{2}\\ln^2 2",
      expectedNumeric: 0.7546938294602481,
      tolerance: 3.1e-4,
      requiredConcepts: ["numeric mismatch rejection"],
      correctRejectionAcceptable: true,
    },
  ],
};

export function getSolverBenchmarkSuite(name = "advanced-math", { limit = 0 } = {}) {
  const suite = SOLVER_BENCHMARK_SUITES[name];
  if (!suite) {
    throw new Error(`Unknown benchmark suite: ${name}`);
  }
  return limit > 0 ? suite.slice(0, limit) : suite;
}
